export const SEARCH_SUBREDDIT = 'SEARCH_SUBREDDIT';
export const SUBMIT_SUBREDDIT = 'SUBMIT_SUBREDDIT';
export const FETCH_SUBS_BEGIN = 'FETCH_SUBS_BEGIN';
export const FETCH_SUBS_SUCCESS = 'FETCH_SUBS_SUCCESS';
export const FETCH_SUBS_FAILURE = 'FETCH_SUBS_FAILURE';
export const DISPLAY_POSTS = 'DISPLAY_POSTS';
export const DISPLAY_POST_COMMENTS = 'DISPLAY_POST_COMMENTS';